### ISSUE TITLE
Query about the RiPPER installation using docker.

### ISSUE THREAD

**Issue by Subhajeet1997** [streptomyces/ripper#5]
I have installed RiPPER using Docker. It was installed successfully. Then, as an example, I have run the suggested command- 
sutripa@Amigo:~$ docker run -it -v /home/tom/rippwork:/home/mnt streptomyces/ripdock
root@485ae2da9606:/home/work# ./ripper_run.sh
rm: cannot remove 'sqlite/*': No such file or directory
python3 /home/work/rodeo2/rodeo_main.py -out /home/mnt/rodout/WP_023840692.1 WP_023840692.1
2023-12-21 11:23:37,158 - entrez_utils - INFO - Fetching WP_023840692.1 data from GenBank.
2023-12-21 11:24:08,521 - entrez_utils - INFO - Parsing WP_023840692.1 handle.
2023-12-21 11:24:11,095 - record_processing - INFO - Worker process 1 is processing WP_023840692.1
2023-12-21 11:24:23,735 - rodeo_main - INFO - Writing output for query #1.      WP_023840692.1
perl /home/work/ripper/ripper.pl -outdir /home/mnt/ripout -- /home/mnt/rodout/WP_023840692.1/main_co_occur.csv
Genbank output is /home/mnt/ripout/WP_023840692.1.gbk. Fasta output is /home/mnt/ripout/WP_023840692.1.faa
TE Line: WP_023840692.1,Frankia sp. CgIS1,NZ_MBLP01000103.1,WP_023840692.1,231988,233389,+,PF02624,YcaO,"YcaO cyclodehydratase, ATP-ad Mg2+-binding",1.1e-51
TE Line:        231988  233389  1
TE index is 8
215189  250188
teNt    NZ_MBLP01000103.1       100.000 1402    0       0       1       1402    25197   26598   0.0     2590
/tmp/rippVIfTH.gbk      206792  241791

Done 1

python3 /home/work/rodeo2/rodeo_main.py -out /home/mnt/rodout/WP_021198358.1 WP_021198358.1
2023-12-21 11:24:52,041 - entrez_utils - INFO - Fetching WP_021198358.1 data from GenBank.
2023-12-21 11:25:16,901 - entrez_utils - INFO - Parsing WP_021198358.1 handle.
2023-12-21 11:25:17,992 - record_processing - INFO - Worker process 1 is processing WP_021198358.1
2023-12-21 11:25:33,818 - rodeo_main - INFO - Writing output for query #1.      WP_021198358.1
perl /home/work/ripper/ripper.pl -outdir /home/mnt/ripout -- /home/mnt/rodout/WP_021198358.1/main_co_occur.csv
Genbank output is /home/mnt/ripout/WP_021198358.1.gbk. Fasta output is /home/mnt/ripout/WP_021198358.1.faa
TE Line: WP_021198358.1,Microbacterium maritypicum MF109,NZ_ATAO01000024.1,WP_021198358.1,31300,29896,-,PF02624,YcaO,"YcaO cyclodehydratase, ATP-ad Mg2+-binding",8.8e-40
TE Line:        29896   31300   -1
TE index is 8
500 Server closed connection without sending any data back <URL:http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nucleotide&id=NZ_ATAO01000024.1&retmode=text&rettype=gbwithparts>
13099   48098
Can't call method "species" on an undefined value at /home/work/ripper/ripper.pl line 459.

Done 2

python3 /home/work/rodeo2/rodeo_main.py -out /home/mnt/rodout/WP_021342369.1 WP_021342369.1
Traceback (most recent call last):
  File "/home/work/rodeo2/rodeo_main.py", line 411, in <module>
    __main__()
  File "/home/work/rodeo2/rodeo_main.py", line 138, in __main__
    mostRecentVersion = urlopen(req, timeout=2.5).read()
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1377, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
TimeoutError: timed out
perl /home/work/ripper/ripper.pl -outdir /home/mnt/ripout -- /home/mnt/rodout/WP_021342369.1/main_co_occur.csv
Genbank output is /home/mnt/ripout/WP_021342369.1.gbk. Fasta output is /home/mnt/ripout/WP_021342369.1.faa
Could not open /home/mnt/rodout/WP_021342369.1/main_co_occur.csv at /home/work/ripper/ripper.pl line 330.

Done 3

python3 /home/work/rodeo2/rodeo_main.py -out /home/mnt/rodout/WP_032759195.1 WP_032759195.1
Traceback (most recent call last):
  File "/home/work/rodeo2/rodeo_main.py", line 411, in <module>
    __main__()
  File "/home/work/rodeo2/rodeo_main.py", line 138, in __main__
    mostRecentVersion = urlopen(req, timeout=2.5).read()
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1377, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
TimeoutError: timed out
perl /home/work/ripper/ripper.pl -outdir /home/mnt/ripout -- /home/mnt/rodout/WP_032759195.1/main_co_occur.csv
Genbank output is /home/mnt/ripout/WP_032759195.1.gbk. Fasta output is /home/mnt/ripout/WP_032759195.1.faa
Could not open /home/mnt/rodout/WP_032759195.1/main_co_occur.csv at /home/work/ripper/ripper.pl line 330.

Done 4

python3 /home/work/rodeo2/rodeo_main.py -out /home/mnt/rodout/WP_044386416.1 WP_044386416.1
Traceback (most recent call last):
  File "/home/work/rodeo2/rodeo_main.py", line 411, in <module>
    __main__()
  File "/home/work/rodeo2/rodeo_main.py", line 138, in __main__
    mostRecentVersion = urlopen(req, timeout=2.5).read()
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1377, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
TimeoutError: timed out
perl /home/work/ripper/ripper.pl -outdir /home/mnt/ripout -- /home/mnt/rodout/WP_044386416.1/main_co_occur.csv
Genbank output is /home/mnt/ripout/WP_044386416.1.gbk. Fasta output is /home/mnt/ripout/WP_044386416.1.faa
Could not open /home/mnt/rodout/WP_044386416.1/main_co_occur.csv at /home/work/ripper/ripper.pl line 330.

Done 5

python3 /home/work/rodeo2/rodeo_main.py -out /home/mnt/rodout/KND23925.1 KND23925.1
2023-12-21 11:26:26,754 - entrez_utils - INFO - Fetching KND23925.1 data from GenBank.
2023-12-21 11:26:50,274 - entrez_utils - INFO - Parsing KND23925.1 handle.
2023-12-21 11:26:53,659 - record_processing - INFO - Worker process 1 is processing KND23925.1
2023-12-21 11:27:09,099 - rodeo_main - INFO - Writing output for query #1.      KND23925.1
perl /home/work/ripper/ripper.pl -outdir /home/mnt/ripout -- /home/mnt/rodout/KND23925.1/main_co_occur.csv
Genbank output is /home/mnt/ripout/KND23925.1.gbk. Fasta output is /home/mnt/ripout/KND23925.1.faa
TE Line: KND23925.1,Streptomyces europaeiscabiei,KQ257788.1,KND23925.1,86175,87543,+,PF02624,YcaO,"YcaO cyclodehydratase, ATP-ad Mg2+-binding",4.4e-38
TE Line:        86175   87543   1
TE index is 8
69360   104359
teNt    KQ257788.1      100.000 1369    0       0       1       1369    16816   18184   0.0     2529
/tmp/rippRJ2gH.gbk      69360   104359

Copying /home/mnt/ripout/KND23925.1.gbk to /home/mnt/orgnamegbk/Streptomyces_europaeiscabiei_KND23925.1.gbk
Copying /home/mnt/ripout/SCK24093.1.gbk to /home/mnt/orgnamegbk/Streptomyces_sp_AmelKG-D3_SCK24093.1.gbk
Copying /home/mnt/ripout/WP_023840692.1.gbk to /home/mnt/orgnamegbk/Frankia_sp_CgIS1_WP_023840692.1.gbk
Copying /home/mnt/ripout/WP_055421506.1.gbk to /home/mnt/orgnamegbk/Streptomyces_pactum_WP_055421506.1.gbk
Copying /home/mnt/ripout/WP_067284698.1.gbk to /home/mnt/orgnamegbk/Streptomyces_jeddahensis_WP_067284698.1.gbk
/home/mnt/rodout/KND23925.1/
        home    mnt     rodout  KND23925.1      5       KND23925.1    ---
/home/mnt/rodout/WP_023420775.1/
        home    mnt     rodout  WP_023420775.1  5       WP_023420775.1    ---
/home/mnt/rodout/WP_023840692.1/
        home    mnt     rodout  WP_023840692.1  5       WP_023840692.1    ---
/home/mnt/rodout/WP_021198358.1/
        home    mnt     rodout  WP_021198358.1  5       WP_021198358.1    ---
/home/mnt/rodout/WP_067284698.1/
        home    mnt     rodout  WP_067284698.1  5       WP_067284698.1    ---
/home/mnt/rodout/WP_055421506.1/
        home    mnt     rodout  WP_055421506.1  5       WP_055421506.1    ---
/home/mnt/rodout/WP_053606694.1/
        home    mnt     rodout  WP_053606694.1  5       WP_053606694.1    ---
/home/mnt/rodout/SCK24093.1/
        home    mnt     rodout  SCK24093.1      5       SCK24093.1    ---
/home/mnt/pna /home/work
1. Checking
2. Similarity searching

        No datafiles detected.
        You must create data files before processing alignments.

Press a key to continue...1
3. Calculating edges
You must have alignments before this step at /home/work/ripper/egn_ni.pl line 1089, <CFG> line 70.
        main::quickPrepTables() called at /home/work/ripper/egn_ni.pl line 230

0
/home/work /home/mnt/pna
Did it run successfully? I am not able to find the output files and also can't locate /home/mnt location where the output files are supposed to be ? Can anyone help me to find out this issue?

**Comment by Subhajeet1997** [comment]
/home/mnt/rodout/WP_023420775.1/
        home    mnt     rodout  WP_023420775.1  5       WP_023420775.1    ---
/home/mnt/rodout/WP_023840692.1/
        home    mnt     rodout  WP_023840692.1  5       WP_023840692.1    ---
/home/mnt/rodout/WP_032779532.1/
        home    mnt     rodout  WP_032779532.1  5       WP_032779532.1    ---
/home/mnt/rodout/WP_021198358.1/
        home    mnt     rodout  WP_021198358.1  5       WP_021198358.1    ---
/home/mnt/rodout/WP_067284698.1/
        home    mnt     rodout  WP_067284698.1  5       WP_067284698.1    ---
/home/mnt/rodout/WP_055421506.1/
        home    mnt     rodout  WP_055421506.1  5       WP_055421506.1    ---
/home/mnt/rodout/WP_053606694.1/
        home    mnt     rodout  WP_053606694.1  5       WP_053606694.1    ---
/home/mnt/rodout/WP_021342369.1/
        home    mnt     rodout  WP_021342369.1  5       WP_021342369.1    ---
/home/mnt/rodout/SCK24093.1/
        home    mnt     rodout  SCK24093.1      5       SCK24093.1    ---
/home/mnt/pna /home/work
1. Checking
2. Similarity searching

        No datafiles detected.
        You must create data files before processing alignments.

Press a key to continue...
3. Calculating edges
You must have alignments before this step at /home/work/ripper/egn_ni.pl line 1089, <CFG> line 70.
        main::quickPrepTables() called at /home/work/ripper/egn_ni.pl line 230


0
/home/work /home/mnt/pna
Please help me to find out the problem!!
